name: Update Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:     

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: platane/snk@master
        with:
          github_user_name: CristianDB1
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Deploy to Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: snake-output 
