name: Update Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecución diaria
  workflow_dispatch:     # Permite ejecución manual

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necesario para poder crear el branch
    
    steps:
      - name: Generate Snake SVG
        uses: platane/snk@master
        with:
          github_user_name: CristianDB1
          svg_out_path: snake.svg
          
      - name: Upload to Snake Branch
        uses: actions/upload-pages-artifact@v1
        with:
          path: snake.svg
          
      - name: Deploy to Branch
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: snake-output
